apiVersion: v1
kind: Pod
metadata:
  name: api-server
  labels:
    name: api-server
    app: api
spec:
  containers: 
  - name: api-server
    image: "gcr.io/carousell-167810/api-server:api-0.0.7"
    ports:
    - containerPort: 8000 
