apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    name: web-server
    app: web
spec:
  containers: 
  - name: web-server
    image: "gcr.io/carousell-167810/web-server:web-0.0.3"
    ports:
    - containerPort: 8080 
