steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['get', 'github.com/ventu-io/go-shortid']
  
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=interview-api"]
    args: ["build", "-o", "api-server", "api"]
    id: "go-build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "src/api/Dockerfile", "-t", "gcr.io/${PROJECT_ID}/api-server:${TAG_NAME}", "."]
    id: "docker-build"

images: ["gcr.io/${PROJECT_ID}/api-server:$TAG_NAME"]
