steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['get', 'github.com/ventu-io/go-shortid']
  
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=interview-api"]
    args: ["install", "api"]
    id: "go-install"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/api-server:0.0.1", "."]
    id: "docker-build"

images: ["gcr.io/${PROJECT_ID}/api-server:0.0.1"]
