steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['get', 'github.com/dghubble/sling']
  
  - name: 'gcr.io/cloud-builders/go'
    args: ['get', 'github.com/yosssi/ace']
  
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=interview-api"]
    args: ["build", "-o", "web-server", "web/app"]
    id: "go-build"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "src/web/Dockerfile", "-t", "gcr.io/${PROJECT_ID}/api-server:${TAG_NAME}", "."]
    id: "docker-build"

images: ["gcr.io/${PROJECT_ID}/web-server:$TAG_NAME"]
